version: '3'
services:
  devops-next-1:
    image: ghcr.io/dri0z/devops-next-1/devops-next-1:master
    container_name: devops-next-1-prod
    restart: always
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production