version: '3'
services:
  devops-next-1:
    build: 
      context: .
    container_name: devops-next-1
    restart: always
    ports:
      - "8080:3000"
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]
    environment:
      - NODE_ENV=development