name: GitHub Actions Demo avec Docker

on:
  push:
    branches:
      - master
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build de l'image Docker
        run: docker build -t ghcr.io/dri0z/devops-next-1/devops-next-1:${{ github.ref_name }} .

      - name: Push de l'image Docker
        run: docker push ghcr.io/dri0z/devops-next-1/devops-next-1:${{ github.ref_name }}

  deploy-master:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Lancement du conteneur Docker sur prod
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd devops-next-1-prod/
            git pull origin master
            sudo /usr/bin/docker compose -f docker-compose.prod.yml pull
            sudo /usr/bin/docker compose -f docker-compose.prod.yml up -d

  deploy-test:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Lancement du conteneur Docker sur test
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd devops-next-1-test/
            git pull origin test
            sudo /usr/bin/docker compose -f docker-compose.test.yml pull
            sudo /usr/bin/docker compose -f docker-compose.test.yml up -d
