name: GitHub Actions Demo avec Docker
run-name: ${{ github.actor }} push sur la master 🚀
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build de l'image Docker
        run: docker build -t ghcr.io/dri0z/devops-next-1/devops-next-1 .

      - name: Push de l'image Docker
        run: docker push ghcr.io/dri0z/devops-next-1/devops-next-1
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      # - name: Docker login en ssh
      #   uses: appleboy/ssh-action@v1
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_KEY }}
      #     port: 22
      #     script: |
      #       echo "${{ secrets.DOCKER_PASSWORD }}" | sudo -S /usr/bin/docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Lancement du conteneur Docker en ssh 
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            git pull origin master
            sudo /usr/bin/docker rm --force devops-next-1 || true
            sudo /usr/bin/docker compose -f docker-compose.prod.yml up -d




